local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    # Configure i18n for this collection.
    i18n:
      structure: multiple_folders
      locales: [en, uk]
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Metadata', name: 'excerpt', widget: 'string', required: false, fields: [
          { label: 'Title', name: 'title', widget: 'string' },
          { label: 'Description', name: 'description', widget: 'string' }
        ]}
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
