local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: 'src/assets/images'
public_folder: '/_astro'

# Configure i18n for this collection.
i18n:
  structure: multiple_folders
  locales: [en, uk]

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    i18n: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', i18n: true }
      - { label: 'Metadata', name: 'metadata', widget: 'object', i18n: true, fields: [
          { label: 'Title', name: 'title', widget: 'string', i18n: true, required: false },
          { label: 'Description', name: 'description', widget: 'string', i18n: true, required: false }
        ]}
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          i18n: true,
          field: { label: 'Tag', name: 'tag', widget: 'string', i18n: true },
        }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown', i18n: true }
